name: ActionHealth
main: com.zeshanaslam.actionhealth.Main
version: 3.3.2
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard]
commands:
  Actionhealth:
    description: Actionhealth main commands.