name: ActionHealth
main: com.zeshanaslam.actionhealth.Main
version: 3.3.5
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard, mcMMO, MythicMobs]
commands:
  Actionhealth:
    description: Actionhealth main commands.