name: ActionHealth
main: com.zeshanaslam.actionhealth.Main
version: 3.3.3
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard, mcMMO]
commands:
  Actionhealth:
    description: Actionhealth main commands.