name: ActionHealth
main: com.zeshanaslam.actionhealth.Main
version: 3.2.9
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard]
commands:
  Actionhealth:
    description: Actionhealth main command.