name: ActionHealth
main: com.zeshanaslam.actionhealth.Main
version: 3.2.8
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard]
commands:
  Actionhealth:
    description: Actionhealth main command.